name: My First Githuib Action
on: [push]
jobs:
    print-hello-world:
        runs-on: ubuntu-latest
        steps:
            - run: echo "hello world Robert!!!!!"
            - run: echo "this is step  number 2"
